### PR TITLE
Allow user to close alert

### PR DESCRIPTION
**Pull request by epletcher72**
Hey @r0b0t3d 
Would you mind merging this code to edit the "No Twitter Accounts Available" alert?

- makes the message slightly more generalized 
- allows it to be closed so that users can continue using the app

### CODE REVIEW

**Comment by r0b0t3d** [comment]
Thanks, @epletcher72

**Comment by epletcher72** [comment]
OC. Would it be possible to push to npm?

**Comment by r0b0t3d** [comment]
@epletcher72 Released 1.1.3

**Comment by epletcher72** [comment]
Thank you!

**Pull request merged**
